services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ob_sql_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=OpenBazaar123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  
    volumes:
      - ob_sql_data:/var/opt/mssql  

  redis:
     image: redis:latest
     container_name: ob_redis_container
     ports:
       - "6379:6379"
     volumes:
       - ob_redis_data:/data

volumes:
  ob_sql_data:
    driver: local
  ob_redis_data:
     driver: local